CREATE TABLE POST(
POST_NO INT PRIMARY KEY,
POST_ID VARCHAR2(20),
POST_CONTENT CLOB, 
POST_LIKE INT,
POST_DATE DATE,
FOREIGN KEY(POST_ID) REFERENCES MEMBER(MEM_ID)ON DELETE CASCADE
);



CREATE TABLE RP(
RP_NO INT PRIMARY KEY,
RP_ID VARCHAR2(20),
RP_CONTENT CLOB,
RP_POST_NO INT,
RP_DATE DATE,
FOREIGN KEY(RP_ID) REFERENCES MEMBER(MEM_ID)ON DELETE CASCADE,
FOREIGN KEY(RP_POST_NO) REFERENCES POST(POST_NO)ON DELETE CASCADE
);

CREATE TABLE TO_LIKE(
LIKE_NO INT PRIMARY KEY,
LIKE_ID VARCHAR2(20),
LIKE_POST_NO INT,
FOREIGN KEY(LIKE_ID) REFERENCES MEMBER(MEM_ID)ON DELETE CASCADE
);

CREATE TABLE POLLOW(
POLLOW_NO INT PRIMARY KEY,
POLLOW_I VARCHAR2(20),
POLLOW_Y VARCHAR2(20),
FOREIGN KEY(POLLOW_I) REFERENCES MEMBER(MEM_ID)ON DELETE CASCADE,
FOREIGN KEY(POLLOW_Y) REFERENCES MEMBER(MEM_ID)ON DELETE CASCADE
);

CREATE TABLE POLLOWER(
POLLOWER_NO INT PRIMARY KEY,
POLLOWER_ID VARCHAR2(20),
POLLOWER_COUNT INT,
FOREIGN KEY(POLLOWER_ID) REFERENCES MEMBER(MEM_ID)ON DELETE CASCADE
);

CREATE TABLE IMG(
IMG_NO INT PRIMARY KEY,
IMG_AD VARCHAR2(200),
IMG_POST INT,
FOREIGN KEY(IMG_POST) REFERENCES POST(POST_NO)ON DELETE CASCADE
);


CREATE TABLE RRP(
RRP_NO INT PRIMARY KEY,
RRP_RPNO INT,
RRP_ID VARCHAR2(20),
RRP_CONTENT CLOB,
RRP_POST_NO INT,
RP_DATE DATE,
FOREIGN KEY(RRP_ID) REFERENCES MEMBER(MEM_ID)ON DELETE CASCADE,
FOREIGN KEY(RRP_POST_NO) REFERENCES POST(POST_NO)ON DELETE CASCADE
);




SELECT * FROM RRP;
DROP TABLE POLLOW;

ROLLBACK;