--------------------------------------------------------
--  파일이 생성됨 - 화요일-9월-29-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SE_FOLLOW
--------------------------------------------------------

   CREATE SEQUENCE  "SNS"."SE_FOLLOW"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 4 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SE_LIKE
--------------------------------------------------------

   CREATE SEQUENCE  "SNS"."SE_LIKE"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SE_PHOTO
--------------------------------------------------------

   CREATE SEQUENCE  "SNS"."SE_PHOTO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SE_POST
--------------------------------------------------------

   CREATE SEQUENCE  "SNS"."SE_POST"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 77 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SE_RP
--------------------------------------------------------

   CREATE SEQUENCE  "SNS"."SE_RP"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SE_RRP
--------------------------------------------------------

   CREATE SEQUENCE  "SNS"."SE_RRP"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table FOLLOW
--------------------------------------------------------

  CREATE TABLE "SNS"."FOLLOW" 
   (	"FOLLOW" NUMBER(*,0), 
	"FOLLOW_I" VARCHAR2(20 BYTE), 
	"FOLLOW_Y" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SNS"."FOLLOW"."FOLLOW" IS '번호';
   COMMENT ON COLUMN "SNS"."FOLLOW"."FOLLOW_I" IS '신청자';
   COMMENT ON COLUMN "SNS"."FOLLOW"."FOLLOW_Y" IS '대상자';
   COMMENT ON TABLE "SNS"."FOLLOW"  IS '팔로우';
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "SNS"."MEMBER" 
   (	"MEM_ID" VARCHAR2(20 BYTE), 
	"MEM_PASS" VARCHAR2(20 BYTE), 
	"MEM_NAME" VARCHAR2(20 BYTE), 
	"MEM_TEL" VARCHAR2(20 BYTE), 
	"MEM_DATE" DATE, 
	"MEM_AUTHOR" VARCHAR2(20 BYTE) DEFAULT 'USER', 
	"MEM_INTRO" VARCHAR2(200 BYTE), 
	"MEM_FOLLOW" NUMBER(*,0) DEFAULT 0, 
	"MEM_FOLLOWER" NUMBER(*,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SNS"."MEMBER"."MEM_ID" IS '아이디';
   COMMENT ON COLUMN "SNS"."MEMBER"."MEM_PASS" IS '비밀번호';
   COMMENT ON COLUMN "SNS"."MEMBER"."MEM_NAME" IS '이름';
   COMMENT ON COLUMN "SNS"."MEMBER"."MEM_TEL" IS '전화번호';
   COMMENT ON COLUMN "SNS"."MEMBER"."MEM_DATE" IS '가입일';
   COMMENT ON COLUMN "SNS"."MEMBER"."MEM_AUTHOR" IS '권한';
   COMMENT ON COLUMN "SNS"."MEMBER"."MEM_INTRO" IS '상태명';
   COMMENT ON COLUMN "SNS"."MEMBER"."MEM_FOLLOW" IS '팔로우';
   COMMENT ON COLUMN "SNS"."MEMBER"."MEM_FOLLOWER" IS '팔로워';
   COMMENT ON TABLE "SNS"."MEMBER"  IS '회원';
--------------------------------------------------------
--  DDL for Table PHOTO
--------------------------------------------------------

  CREATE TABLE "SNS"."PHOTO" 
   (	"PHO_NO" NUMBER(*,0), 
	"PHO_PHOTO" VARCHAR2(255 BYTE), 
	"PHO_POSTNO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POST
--------------------------------------------------------

  CREATE TABLE "SNS"."POST" 
   (	"POST_NO" NUMBER(*,0), 
	"POST_ID" VARCHAR2(20 BYTE), 
	"POST_CONTENT" CLOB, 
	"POST_LIKE" NUMBER(*,0), 
	"POST_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("POST_CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "SNS"."POST"."POST_NO" IS '게시글번호';
   COMMENT ON COLUMN "SNS"."POST"."POST_ID" IS '작성';
   COMMENT ON COLUMN "SNS"."POST"."POST_CONTENT" IS '내용';
   COMMENT ON COLUMN "SNS"."POST"."POST_LIKE" IS '좋아요';
   COMMENT ON COLUMN "SNS"."POST"."POST_DATE" IS '게시일';
   COMMENT ON TABLE "SNS"."POST"  IS '게시글';
--------------------------------------------------------
--  DDL for Table POST_LIKE
--------------------------------------------------------

  CREATE TABLE "SNS"."POST_LIKE" 
   (	"LIKE_NO" NUMBER(*,0), 
	"LIKE_POST_NO" NUMBER(*,0), 
	"LIKE_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SNS"."POST_LIKE"."LIKE_NO" IS '좋아요번호';
   COMMENT ON COLUMN "SNS"."POST_LIKE"."LIKE_POST_NO" IS '게시글번호';
   COMMENT ON COLUMN "SNS"."POST_LIKE"."LIKE_ID" IS '아이디';
   COMMENT ON TABLE "SNS"."POST_LIKE"  IS '좋아요';
--------------------------------------------------------
--  DDL for Table RP
--------------------------------------------------------

  CREATE TABLE "SNS"."RP" 
   (	"RP_NO" NUMBER(*,0), 
	"RP_CONTENT" CLOB, 
	"RP_DATE" DATE, 
	"RP_POST_NO" NUMBER(*,0), 
	"RP_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("RP_CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "SNS"."RP"."RP_NO" IS '댓글번호';
   COMMENT ON COLUMN "SNS"."RP"."RP_CONTENT" IS '내용';
   COMMENT ON COLUMN "SNS"."RP"."RP_DATE" IS '게시일';
   COMMENT ON COLUMN "SNS"."RP"."RP_POST_NO" IS '게시글번호';
   COMMENT ON COLUMN "SNS"."RP"."RP_ID" IS '작성자';
   COMMENT ON TABLE "SNS"."RP"  IS '댓글';
--------------------------------------------------------
--  DDL for Table RRP
--------------------------------------------------------

  CREATE TABLE "SNS"."RRP" 
   (	"RRP_NO" NUMBER(*,0), 
	"RRP_ID" VARCHAR2(20 BYTE), 
	"RRP_RPNO" NUMBER(*,0), 
	"RRP_CONTENT" CLOB, 
	"RRP_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("RRP_CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "SNS"."RRP"."RRP_NO" IS '답글번호';
   COMMENT ON COLUMN "SNS"."RRP"."RRP_ID" IS '작성자';
   COMMENT ON COLUMN "SNS"."RRP"."RRP_RPNO" IS '댓글번호';
   COMMENT ON COLUMN "SNS"."RRP"."RRP_CONTENT" IS '내용';
   COMMENT ON COLUMN "SNS"."RRP"."RRP_DATE" IS '답글게시일';
   COMMENT ON TABLE "SNS"."RRP"  IS '답글';
REM INSERTING into SNS.FOLLOW
SET DEFINE OFF;
REM INSERTING into SNS.MEMBER
SET DEFINE OFF;
Insert into SNS.MEMBER (MEM_ID,MEM_PASS,MEM_NAME,MEM_TEL,MEM_DATE,MEM_AUTHOR,MEM_INTRO,MEM_FOLLOW,MEM_FOLLOWER) values ('admin','1234','admin','123',to_date('20/09/28','RR/MM/DD'),'ADMIN','1',1,2);
Insert into SNS.MEMBER (MEM_ID,MEM_PASS,MEM_NAME,MEM_TEL,MEM_DATE,MEM_AUTHOR,MEM_INTRO,MEM_FOLLOW,MEM_FOLLOWER) values ('6','qwer','qwer','123',to_date('20/09/28','RR/MM/DD'),'USER','1',1,2);
REM INSERTING into SNS.PHOTO
SET DEFINE OFF;
REM INSERTING into SNS.POST
SET DEFINE OFF;
Insert into SNS.POST (POST_NO,POST_ID,POST_LIKE,POST_DATE) values (37,'admin',0,to_date('20/09/28','RR/MM/DD'));
Insert into SNS.POST (POST_NO,POST_ID,POST_LIKE,POST_DATE) values (38,'admin',0,to_date('20/09/28','RR/MM/DD'));
Insert into SNS.POST (POST_NO,POST_ID,POST_LIKE,POST_DATE) values (39,'admin',0,to_date('20/09/28','RR/MM/DD'));
Insert into SNS.POST (POST_NO,POST_ID,POST_LIKE,POST_DATE) values (40,'admin',0,to_date('20/09/28','RR/MM/DD'));
Insert into SNS.POST (POST_NO,POST_ID,POST_LIKE,POST_DATE) values (41,'admin',0,to_date('20/09/28','RR/MM/DD'));
Insert into SNS.POST (POST_NO,POST_ID,POST_LIKE,POST_DATE) values (42,'admin',0,to_date('20/09/28','RR/MM/DD'));
Insert into SNS.POST (POST_NO,POST_ID,POST_LIKE,POST_DATE) values (43,'admin',0,to_date('20/09/28','RR/MM/DD'));
Insert into SNS.POST (POST_NO,POST_ID,POST_LIKE,POST_DATE) values (44,'admin',0,to_date('20/09/28','RR/MM/DD'));
Insert into SNS.POST (POST_NO,POST_ID,POST_LIKE,POST_DATE) values (45,'admin',0,to_date('20/09/28','RR/MM/DD'));
Insert into SNS.POST (POST_NO,POST_ID,POST_LIKE,POST_DATE) values (46,'admin',0,to_date('20/09/28','RR/MM/DD'));
Insert into SNS.POST (POST_NO,POST_ID,POST_LIKE,POST_DATE) values (47,'admin',0,to_date('20/09/28','RR/MM/DD'));
Insert into SNS.POST (POST_NO,POST_ID,POST_LIKE,POST_DATE) values (48,'admin',0,to_date('20/09/28','RR/MM/DD'));
Insert into SNS.POST (POST_NO,POST_ID,POST_LIKE,POST_DATE) values (49,'admin',0,to_date('20/09/28','RR/MM/DD'));
Insert into SNS.POST (POST_NO,POST_ID,POST_LIKE,POST_DATE) values (50,'admin',0,to_date('20/09/28','RR/MM/DD'));
Insert into SNS.POST (POST_NO,POST_ID,POST_LIKE,POST_DATE) values (51,'admin',0,to_date('20/09/28','RR/MM/DD'));
Insert into SNS.POST (POST_NO,POST_ID,POST_LIKE,POST_DATE) values (52,'admin',0,to_date('20/09/28','RR/MM/DD'));
Insert into SNS.POST (POST_NO,POST_ID,POST_LIKE,POST_DATE) values (53,'admin',0,to_date('20/09/28','RR/MM/DD'));
Insert into SNS.POST (POST_NO,POST_ID,POST_LIKE,POST_DATE) values (54,'admin',0,to_date('20/09/28','RR/MM/DD'));
Insert into SNS.POST (POST_NO,POST_ID,POST_LIKE,POST_DATE) values (55,'admin',0,to_date('20/09/28','RR/MM/DD'));
REM INSERTING into SNS.POST_LIKE
SET DEFINE OFF;
REM INSERTING into SNS.RP
SET DEFINE OFF;
REM INSERTING into SNS.RRP
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_RRP
--------------------------------------------------------

  CREATE UNIQUE INDEX "SNS"."PK_RRP" ON "SNS"."RRP" ("RRP_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_FOLLOW
--------------------------------------------------------

  CREATE UNIQUE INDEX "SNS"."PK_FOLLOW" ON "SNS"."FOLLOW" ("FOLLOW") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MEMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX "SNS"."PK_MEMBER" ON "SNS"."MEMBER" ("MEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_POST_LIKE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SNS"."PK_POST_LIKE" ON "SNS"."POST_LIKE" ("LIKE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_POST
--------------------------------------------------------

  CREATE UNIQUE INDEX "SNS"."PK_POST" ON "SNS"."POST" ("POST_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_RP
--------------------------------------------------------

  CREATE UNIQUE INDEX "SNS"."PK_RP" ON "SNS"."RP" ("RP_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table RRP
--------------------------------------------------------

  ALTER TABLE "SNS"."RRP" ADD CONSTRAINT "PK_RRP" PRIMARY KEY ("RRP_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SNS"."RRP" MODIFY ("RRP_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOLLOW
--------------------------------------------------------

  ALTER TABLE "SNS"."FOLLOW" ADD CONSTRAINT "PK_FOLLOW" PRIMARY KEY ("FOLLOW")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SNS"."FOLLOW" MODIFY ("FOLLOW" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POST
--------------------------------------------------------

  ALTER TABLE "SNS"."POST" ADD CONSTRAINT "PK_POST" PRIMARY KEY ("POST_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SNS"."POST" MODIFY ("POST_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PHOTO
--------------------------------------------------------

  ALTER TABLE "SNS"."PHOTO" ADD PRIMARY KEY ("PHO_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POST_LIKE
--------------------------------------------------------

  ALTER TABLE "SNS"."POST_LIKE" ADD CONSTRAINT "PK_POST_LIKE" PRIMARY KEY ("LIKE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SNS"."POST_LIKE" MODIFY ("LIKE_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RP
--------------------------------------------------------

  ALTER TABLE "SNS"."RP" ADD CONSTRAINT "PK_RP" PRIMARY KEY ("RP_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SNS"."RP" MODIFY ("RP_ID" NOT NULL ENABLE);
  ALTER TABLE "SNS"."RP" MODIFY ("RP_POST_NO" NOT NULL ENABLE);
  ALTER TABLE "SNS"."RP" MODIFY ("RP_DATE" NOT NULL ENABLE);
  ALTER TABLE "SNS"."RP" MODIFY ("RP_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SNS"."RP" MODIFY ("RP_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "SNS"."MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY ("MEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SNS"."MEMBER" ADD CONSTRAINT "MEM_AUTHOR" CHECK (MEM_AUTHOR IN('ADMIN','USER')) ENABLE;
  ALTER TABLE "SNS"."MEMBER" MODIFY ("MEM_FOLLOWER" NOT NULL ENABLE);
  ALTER TABLE "SNS"."MEMBER" MODIFY ("MEM_FOLLOW" NOT NULL ENABLE);
  ALTER TABLE "SNS"."MEMBER" MODIFY ("MEM_DATE" NOT NULL ENABLE);
  ALTER TABLE "SNS"."MEMBER" MODIFY ("MEM_TEL" NOT NULL ENABLE);
  ALTER TABLE "SNS"."MEMBER" MODIFY ("MEM_NAME" NOT NULL ENABLE);
  ALTER TABLE "SNS"."MEMBER" MODIFY ("MEM_PASS" NOT NULL ENABLE);
  ALTER TABLE "SNS"."MEMBER" MODIFY ("MEM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table FOLLOW
--------------------------------------------------------

  ALTER TABLE "SNS"."FOLLOW" ADD CONSTRAINT "FK_MEMBER_TO_FOLLOW" FOREIGN KEY ("FOLLOW_I")
	  REFERENCES "SNS"."MEMBER" ("MEM_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SNS"."FOLLOW" ADD CONSTRAINT "FK_MEMBER_TO_FOLLOW2" FOREIGN KEY ("FOLLOW_Y")
	  REFERENCES "SNS"."MEMBER" ("MEM_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PHOTO
--------------------------------------------------------

  ALTER TABLE "SNS"."PHOTO" ADD CONSTRAINT "FK_POSTNO" FOREIGN KEY ("PHO_POSTNO")
	  REFERENCES "SNS"."POST" ("POST_NO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POST
--------------------------------------------------------

  ALTER TABLE "SNS"."POST" ADD CONSTRAINT "FK_MEMBER_TO_POST" FOREIGN KEY ("POST_ID")
	  REFERENCES "SNS"."MEMBER" ("MEM_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POST_LIKE
--------------------------------------------------------

  ALTER TABLE "SNS"."POST_LIKE" ADD CONSTRAINT "FK_MEMBER_TO_POST_LIKE" FOREIGN KEY ("LIKE_ID")
	  REFERENCES "SNS"."MEMBER" ("MEM_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SNS"."POST_LIKE" ADD CONSTRAINT "FK_POST_TO_POST_LIKE" FOREIGN KEY ("LIKE_POST_NO")
	  REFERENCES "SNS"."POST" ("POST_NO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RP
--------------------------------------------------------

  ALTER TABLE "SNS"."RP" ADD CONSTRAINT "FK_MEMBER_TO_RP" FOREIGN KEY ("RP_ID")
	  REFERENCES "SNS"."MEMBER" ("MEM_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SNS"."RP" ADD CONSTRAINT "FK_POST_TO_RP" FOREIGN KEY ("RP_POST_NO")
	  REFERENCES "SNS"."POST" ("POST_NO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RRP
--------------------------------------------------------

  ALTER TABLE "SNS"."RRP" ADD CONSTRAINT "FK_MEMBER_TO_RRP" FOREIGN KEY ("RRP_ID")
	  REFERENCES "SNS"."MEMBER" ("MEM_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SNS"."RRP" ADD CONSTRAINT "FK_RP_TO_RRP" FOREIGN KEY ("RRP_RPNO")
	  REFERENCES "SNS"."POST" ("POST_NO") ON DELETE CASCADE ENABLE;
